apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secretName}}
  labels:
    app.kubernetes.io/name: {{ include "openapi2apigee.name" . }}
    helm.sh/chart: {{ include "openapi2apigee.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
type: Opaque
stringData:
  username: {{.Values.apigee.username}}
  password: {{.Values.apigee.password}}
